services:
  php:
    build: .
    container_name: codeigniter_php
    user: "1000:1000"
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    depends_on:
      - redis
    environment:
      - DOCKER_ENV=1

  nginx:
    image: nginx:latest
    container_name: codeigniter_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: codeigniter_redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network: